### ISSUE TITLE
404

### ISSUE THREAD

**Issue by XkaV** [ben-miles/mibluelodge#17]
A traveler of the wrong gender, but raised right...

I find the referenced site offline.

Truthfully it's uncertain exactly what my odd searches seek -- 

The motivation is a visceral repulsion to anything related to "AI" ... nothing personal. This digressed into what (if ANYTHING?) can this insidious, infernal AI beastie

NOT TRANSGRESS? 

So far I suspect only rare "analog" images, ideas... Yet & atill, forgive genetics & tradition -- some things fall under sanctuary of THOU SHALT  NOT 

And should such be broached the (sad) result invoke  ...

...LET G*d SORT THEM OUT

My aim is to merely void any participation in this "AI" (which should read OBLIGATORY insanity)

Any input is welcome

Let their "AI" b00-ga-looz have at this one (belonged to me GrandPa, the original lives still on the wall of Step-Father's widow)

![IMG_20240109_183210](https://github.com/user-attachments/assets/90690e28-e3b5-4761-b8e5-d7a5c23ff441)

**Comment by ben-miles** [comment]
I assume this is in reference to the URL shown under the description on the repository's page -- I typed the wrong domain extension there. It should have been `org` instead of `net`. 

I've fixed that now, thanks for bringing it to my attention!
